apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configure-rhacs-authentication
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: stackrox
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: stackrox.central.adminUser
          value: admin
        - name: stackrox.central.adminPassword
          value: 0mh6mZCZ
    path: charts/rhacs-authentication/configure-multiuser
    repoURL: 'https://github.com/treddy08/rhdp-workloads'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - jsonPointers:
        - /metadata/labels
      kind: ServiceAccount
    - jsonPointers:
        - /metadata/labels
      kind: ClusterRoleBinding