apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configure-rhacs-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: rhacs-operator
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: charts/rhacs/install-rhacs-operator
    repoURL: 'https://github.com/treddy08/rhdp-workloads'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - PruneLast=true
