apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configure-stackrox
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: stackrox
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: stackrox.central.adminUser
          value: admin
        - name: stackrox.central.adminPassword
          value: 0mh6mZCZ
    path: charts/rhacs/configure-stackrox
    repoURL: 'https://github.com/treddy08/rhdp-workloads'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true