apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp4-workload-rhacs-authentication
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: ocp4-workload-rhacs-authentication
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: rhacs.central.adminUser
          value: admin
        - name: rhacs.central.adminPassword
          value: 0mh6mZCZ
    path: charts/ocp4-workload-rhacs-authentication
    repoURL: 'https://github.com/treddy08/rhdp-workloads'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - jsonPointers:
        - /metadata/labels
      kind: ServiceAccount
    - jsonPointers:
        - /metadata/labels/app.kubernetes.io~1instance
      kind: ClusterRoleBinding