apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp4-workload-authentication
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: ocp4-workload-authentication
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: authentication.adminUser
          value: opentlc-mgr
        - name: authentication.htpasswd.adminPassword
          value: r3dh4t1!
        - name: authentication.htpasswd.userPassword
          value: openshift
    path: charts/authentication/configure-authentication
    repoURL: 'https://github.com/treddy08/rhdp-workloads'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true